version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/easy-crm-backend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 99

  - package-ecosystem: "npm"
    directory: "/easy-crm-frontend"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 99
