spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/postgres
    username: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/master
