services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5444:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # before starting this service, create a database named "keycloak" in the postgres container manually
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: dev
      KC_BOOTSTRAP_ADMIN_PASSWORD: dev
    command: start-dev
    depends_on:
      - postgres
    ports:
      - "8090:8080"
