name: Build Vue

on: [push]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'nstdspace'
          reponame: 'VueTableTest'
          token: ${{ secrets.GITHUB_TOKEN }}
